### ISSUE TITLE
Correct orientation on photo upload

### ISSUE THREAD

**Issue by superpowers11** [gordon-cs/Project-Phoenix#103]
* Pictures uploaded from mobile are rotated 90 degrees to the left.
* Potential fix: check the exif meta tags for 'Orientation'. This [library](https://github.com/blueimp/JavaScript-Load-Image#exif-parser) might be useful.

**Comment by eanyanwu** [comment]
The DNS records for rci and rcitrain have been temporarily disabled for now by NSG folks.
So I can't continue testing this atm. Will do so once the DNS records go back up.

**Comment by eanyanwu** [comment]
❌  Won't fix as users have not complained about this. (Maybe it's working for everyone 🤷‍♂️ )
I'll tag it as a potential task a new contributor can take a look at.
