### ISSUE TITLE
Photo Upload on Checkout

### ISSUE THREAD

**Issue by superpowers11** [gordon-cs/Project-Phoenix#116]
* Enable RD/RA  users to upload photos when they assign a charge during checkout, in order to document what the Resident is being charged for.
* This will look very similar to photo upload during the RCI input use cases.
* It  involve adding a new column to the `Fine` table, which will be something like `DamageImagePath`
* Do we want an image modal for each fine? That may be excessive. Perhaps just decently sized images instead of thumbnails.

**Comment by eanyanwu** [comment]
❌  won't be doing this.
RDs can continue taking pictures separately.
This could be a potential task for the next maintainer. 👍
