### ISSUE TITLE
User Error Responses

### ISSUE THREAD

**Issue by superpowers11** [gordon-cs/Project-Phoenix#154]
Work on error-handling and throwing exceptions in general across the site. Because we may not have a maintainer or team of people who deeply know the system to identify what is going wrong, we need to make the system more informative about what is happening when something goes wrong.

**Comment by eanyanwu** [comment]
I'll leave this open for now. I think there is still some more exception handling that can be done. 
The pull request just handled the most obvious one.

**Comment by eanyanwu** [comment]
✔️  Will be doing this before Checkin this year.

**Comment by eanyanwu** [comment]
👍  Done.
I'll be writing a bit about how i am handling exceptions in the ReadMe
