### ISSUE TITLE
Add logging abilities

### ISSUE THREAD

**Issue by superpowers11** [gordon-cs/Project-Phoenix#157]
Set up logging functionality - need to figure out the infrastructure for logging

**Comment by eanyanwu** [comment]
Currently thinking about this while I wait on the test accounts to be created.
I am thinking that the most useful logs are those of exceptions. So we can have something as simple as:
(_Time_ : Exception)

[This msdn article](https://msdn.microsoft.com/en-us/library/gg416513(VS.98).aspx) suggests Exception filters as one way to the implement the logging. 
What do you think?

**Comment by superpowers11** [comment]
Exception filters seem like a decent way to go. I briefly looked over the article; would you use the `OnException` method override?
I did a quick web search on error logging in C# MVC and something called ELMAH came up a few times - a NuGet package to facilitate logging. Have you heard of it? This [blog](http://www.hanselman.com/blog/ELMAHErrorLoggingModulesAndHandlersForASPNETAndMVCToo.aspx) explains it briefly, and here is the [home page](https://elmah.io/?utm_source=blogpopup&utm_medium=blog&utm_campaign=blogpopup)

**Comment by eanyanwu** [comment]
I've heard the name, never knew what it did, but wow. It is amazing. I think the best part is the notification via slack/email etc... Unfortunately it isn't free :/
https://elmah.io/pricing/

**Comment by superpowers11** [comment]
That's ok, we can just take it out of the abundant budget the board of trustees has generously issued to this important work for the College. ._.

**Comment by eanyanwu** [comment]
Lol. I'll briefly looking to see if there are other alternatives that have a similar setup...stay tuned

**Comment by eanyanwu** [comment]
Ok, so I read the 60% of [this](https://dusted.codes/demystifying-aspnet-mvc-5-error-pages-and-error-logging) and skimmed the rest.
Summary:
There are a few options with pros and cons depending on what we need. The first section is actually pretty informative. ELMAH is mentioned and briefly explained at the very end too.

What I think we need:
- A developer maintaining this project shouldn't have a hard time finding the source of the problem when ResLife shoots her an email saying "The online rci system is not working". 🤕 

Anything else you can think of?
