### ISSUE TITLE
Top logo spaced oddly in IE

### ISSUE THREAD

**Issue by superpowers11** [gordon-cs/Project-Phoenix#170]
In IE, the Gordon College logo at the top left is slightly misshapen and too low in the layout. The back button also is laid out incorrectly (seen on a specific RCI page). 
![screen shot 2017-08-17 at 4 34 51 pm](https://user-images.githubusercontent.com/15350106/29432607-46d88e6c-836a-11e7-822e-7faa40d17cad.png)
![screen shot 2017-08-17 at 4 34 41 pm](https://user-images.githubusercontent.com/15350106/29432610-49c41272-836a-11e7-86a5-ec37c4d02fdf.png)

**Comment by eanyanwu** [comment]
IE-Driven-Development

I'll take a look at it after checkin happens :)
