### ISSUE TITLE
Safari - older versions don't support `let` variables in js

### ISSUE THREAD

**Issue by superpowers11** [gordon-cs/Project-Phoenix#89]
* We need to figure out a workaround in order to support older versions of Safari.

**Comment by eanyanwu** [comment]
Should we still worry about this?

**Comment by superpowers11** [comment]
Good question, I thought about this later, and realized it was possible that I simply had not updated my Safari for quite awhile. 🐐  Idk if it is likely that users also would have outdated versions of Safari? I suppose it's quite possible. Many people are update shy.

**Comment by eanyanwu** [comment]
I think it is the safari update. All modern browsers support the `let` variable.
http://kangax.github.io/compat-table/es6/#test-let

Might not be worth it to (1) add a javascript transpolar e.g. (babel) or (2) change all `let` to `var`

**Comment by eanyanwu** [comment]
I don't think there are any more `lets` in the code, but I'll make sure. 
We'll stick to using `var`
